# Generated by Django 5.0 on 2024-02-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_app', '0006_image_soura'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='soura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian_app.soura'),
        ),
    ]
