# Generated by Django 5.0 on 2024-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_app', '0007_image_soura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
    ]
