# Generated by Django 5.0 on 2024-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_app', '0008_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
