# Generated by Django 5.0 on 2024-02-16 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_app', '0010_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 9, 0, 24, 459817, tzinfo=datetime.timezone.utc)),
        ),
    ]
