# Generated by Django 5.0 on 2024-02-16 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_app', '0011_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
