# Generated by Django 5.0 on 2024-02-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian_app', '0012_alter_test_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
