# Generated by Django 5.0 on 2024-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='counter',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
