# Generated by Django 5.0 on 2024-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_test_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
