# Generated by Django 5.0 on 2024-02-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_guard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='counter',
            new_name='serial',
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
